# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json

reviews:
  profile: assertive
  request_changes_workflow: true
  auto_review:
    enabled: true
    auto_incremental_review: true

pre_merge_checks:
  docstrings:
    mode: warning
  title:
    mode: warning
  description:
    mode: warning
  issue_assessment:
    mode: warning
