#!/usr/bin/env python
from __future__ import absolute_import
import os
import stat
import subprocess
import sys

from trashcli.restore.main import main as python_main


def _path_is_executable(path):
    return os.path.isfile(path) and (os.stat(path).st_mode & stat.S_IXUSR)


def main():
    root = os.path.realpath(os.path.dirname(__file__))
    candidate = os.environ.get(
        "TRASH_RESTORE_BINARY",
        os.path.join(root, "trash-restore-rs", "target", "release", "trash-restore"),
    )
    if _path_is_executable(candidate):
        code = subprocess.call([candidate] + sys.argv[1:])
        sys.exit(code)

    sys.exit(python_main())


if __name__ == "__main__":
    main()
