name: "Secret Scanning"
on: [push, pull_request]
jobs:
  scan:
    name: Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run secret scanning
        uses: github/codeql-action/secret-scanning@v3
